#!/usr/bin/env python3
"""
inventory_gen.py - Generate Ansible inventory from Pulumi stack outputs.

Reads relay_nodes and backend outputs from a Pulumi stack and renders
ansible/inventory/<stack>.yml, preserving the exact schema expected by
the existing Ansible roles.

Usage:
  python infra/inventory_gen.py --stack production
  python infra/inventory_gen.py --stack staging

The generated file is placed at ansible/inventory/<stack>.yml and is
prepended with a warning comment. Do not edit the generated file manually
- run this script again after any infrastructure change.

Requirements:
  - pulumi CLI must be installed and authenticated (pulumi login ...)
  - The target stack must have been deployed (pulumi up --stack <stack>)
  - PyYAML (pip install pyyaml)
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path


# Repo root relative to this file's location (infra/ -> ../)
REPO_ROOT = Path(__file__).resolve().parent.parent
INFRA_DIR  = REPO_ROOT / "infra"
INVENTORY_DIR = REPO_ROOT / "ansible" / "inventory"

HEADER = """\
# Generated by infra/inventory_gen.py from Pulumi stack outputs.
# Do not edit this file manually.
# To regenerate: python infra/inventory_gen.py --stack {stack}
#
# Groups:
#   {stack}         - all {stack} hosts (triggers playbooks/group_vars/{stack}/ auto-load)
#   relay_servers   - hosts running relay-xdp + kernel module
#   backend_servers - hosts running relay-backend + Redis
"""


def get_stack_outputs(stack: str) -> dict:
    """Run `pulumi stack output --json` and return parsed dict."""
    result = subprocess.run(
        ["pulumi", "stack", "output", "--json", "--stack", stack],
        cwd=str(INFRA_DIR),
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"ERROR: pulumi stack output failed:\n{result.stderr}", file=sys.stderr)
        sys.exit(1)

    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        print(f"ERROR: failed to parse pulumi output as JSON: {exc}", file=sys.stderr)
        sys.exit(1)


def build_inventory(outputs: dict, stack: str) -> dict:
    """
    Build the Ansible inventory dict from Pulumi stack outputs.

    Output schema:

      all:
        vars:
          ansible_python_interpreter: /usr/bin/python3
        children:
          staging:                        # or production - triggers group_vars auto-load
            children:
              relay_servers:
                hosts:
                  relay-staging-1:
                    ansible_host: <public_ip>
                    relay_name: relay-staging-1
                    ansible_user: ubuntu
              backend_servers:
                hosts:
                  backend-staging-1:
                    ansible_host: <public_ip>
                    ansible_user: ubuntu
    """
    relay_nodes: dict = outputs.get("relay_nodes", {})
    backend: dict = outputs.get("backend", {})

    if not relay_nodes:
        print("ERROR: no relay_nodes in stack outputs. Has `pulumi up` been run?",
              file=sys.stderr)
        sys.exit(1)

    if not backend:
        print("ERROR: no backend in stack outputs. Has `pulumi up` been run?",
              file=sys.stderr)
        sys.exit(1)

    # Build relay_servers hosts dict - sorted by node name for determinism.
    relay_hosts: dict = {}
    for name in sorted(relay_nodes.keys()):
        node = relay_nodes[name]
        relay_hosts[name] = {
            "ansible_host": node["public_ip"],
            "relay_name":   name,
            "ansible_user": "ubuntu",
        }

    backend_name: str = backend.get("name", f"backend-{stack}-1")
    backend_hosts: dict = {
        backend_name: {
            "ansible_host": backend["public_ip"],
            "ansible_user": "ubuntu",
        }
    }

    return {
        "all": {
            "vars": {
                "ansible_python_interpreter": "/usr/bin/python3",
            },
            "children": {
                # Environment group - causes Ansible to auto-load
                # playbooks/group_vars/<stack>/vars.yml and vault.yml
                stack: {
                    "children": {
                        "relay_servers": {
                            "hosts": relay_hosts,
                        },
                        "backend_servers": {
                            "hosts": backend_hosts,
                        },
                    },
                },
            },
        }
    }


def render_yaml(inventory: dict) -> str:
    """Render inventory dict to YAML string without aliases."""
    import yaml  # imported here so missing PyYAML gives a clear error

    class _NoAliasDumper(yaml.Dumper):
        def ignore_aliases(self, _data):
            return True

    return yaml.dump(
        inventory,
        Dumper=_NoAliasDumper,
        default_flow_style=False,
        sort_keys=True,
        allow_unicode=True,
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate ansible/inventory/<stack>.yml from Pulumi stack outputs."
    )
    parser.add_argument(
        "--stack",
        required=True,
        choices=["production", "staging"],
        help="Pulumi stack name to read outputs from.",
    )
    args = parser.parse_args()
    stack: str = args.stack

    print(f"Reading Pulumi stack outputs for stack: {stack} ...")
    outputs = get_stack_outputs(stack)

    print("Building Ansible inventory ...")
    inventory = build_inventory(outputs, stack)

    out_path = INVENTORY_DIR / f"{stack}.yml"
    INVENTORY_DIR.mkdir(parents=True, exist_ok=True)

    header = HEADER.format(stack=stack)
    content = header + render_yaml(inventory)
    out_path.write_text(content, encoding="utf-8")

    print(f"Written: {out_path}")
    print()
    print("Next step:")
    print(f"  cd ansible && ansible-playbook -i inventory/{stack}.yml "
          f"playbooks/site.yml --ask-vault-pass -e relay_version=<ver>")


if __name__ == "__main__":
    main()

