config:
  relay-xdp-infra:relay_regions:
    - us-east-1
    - eu-west-1
    - ap-southeast-1
  relay-xdp-infra:relay_count: "3"
  relay-xdp-infra:relay_instance_type: c5n.xlarge
  relay-xdp-infra:backend_region: us-east-1
  relay-xdp-infra:backend_instance_type: c5.large
  relay-xdp-infra:key_pub_path: ~/.ssh/personal-key.pub
  relay-xdp-infra:admin_cidr: 0.0.0.0/0

