#!/usr/bin/env bash
# tests/gen-test-keys.sh - Print test X25519 keypairs for Docker Compose integration tests.
#
# These keys are deterministic (derived from SHA-256 of seed strings) and are
# used ONLY for testing. Never use these keys in production.
#
# The keypairs were generated by:
#   1. SHA-256(seed) -> 32-byte secret key
#   2. X25519 scalar multiplication -> 32-byte public key
#   3. Base64 encode both
#
# To regenerate, create a temp Rust test that uses x25519_dalek::StaticSecret::from()
# with the SHA-256 hash of each seed, then PublicKey::from(&secret).

set -euo pipefail

cat << 'EOF'
=== Test Keypairs for Docker Compose Integration Tests ===

Backend:
  Seed:    "test-backend"
  Private: CW9sqURAaD39bCsrcYKt753Ci7y811INpzzhcvZ0taA=
  Public:  uiaT926BEMSB10asfvgiCi9QkqiLLP/4vVc7sPBfQgo=

Relay-A (172.28.0.10:40000):
  Seed:    "test-relay-a"
  Private: H6iGJ9up0NETlGaSiyKg28L8WUD7SAqxIK1GMNYFT3g=
  Public:  PzdO4BakLhxG5B9REqJkcwb0DZSh4PYH3wdV8FGH8DQ=

Relay-B (172.28.0.11:40000):
  Seed:    "test-relay-b"
  Private: Lht905489TXkG3+4ME+oJIGsTn4b364CgcHhuj9vvGU=
  Public:  +H8U9M1i36CnRt09I97/XuJXoEYowLIFbjQPcZ+rkFY=

Relay-C (172.28.0.12:40000):
  Seed:    "test-relay-c"
  Private: q0O56yUxItge0wtv5rtHmTeKzHL9R8qLJFW7uhCrK4U=
  Public:  gX0jT3+lgWASRX9Whw3m8oChi+sFQvwZUnWMIFatsWQ=

These keys are hardcoded in:
  - tests/fixtures/test-relays.json (relay public keys)
  - docker-compose.test.yml (all keys as env vars)
EOF

