/* relay-sdk - Auto-generated by cbindgen. DO NOT EDIT. */

#ifndef RELAY_GENERATED_H
#define RELAY_GENERATED_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define relay_REPLAY_PROTECTION_BUFFER_SIZE 1024

#define relay_PING_HISTORY_ENTRY_COUNT 1024

#define relay_PING_SAFETY 1.0

#define relay_BANDWIDTH_LIMITER_INTERVAL 1.0

#define relay_PACKET_LOSS_TRACKER_HISTORY 1024

#define relay_PACKET_LOSS_TRACKER_SAFETY 30

#define relay_ADDRESS_NONE 0

#define relay_ADDRESS_IPV4 1

#define relay_ADDRESS_IPV6 2

#define relay_ADDRESS_BYTES_IPV4 6

#define relay_ADDRESS_BYTES 19

#define relay_IPV4_HEADER_BYTES 20

#define relay_UDP_HEADER_BYTES 8

/**
 * Relay packet header (sequence + session_id + session_version + SHA-256 prefix).
 */
#define relay_HEADER_BYTES 25

/**
 * Maximum packet buffer size.
 */
#define relay_MAX_PACKET_BYTES 1384

/**
 * Maximum relay payload (MTU).
 */
#define relay_MTU 1200

/**
 * Byte offset of packet body (after type + pittle + chonkle = 18 bytes).
 */
#define relay_PACKET_BODY_OFFSET 18

#define relay_SESSION_PRIVATE_KEY_BYTES 32

#define relay_ENCRYPTED_ROUTE_TOKEN_BYTES 111

#define relay_ENCRYPTED_CONTINUE_TOKEN_BYTES 57

#define relay_MAX_TOKENS 7

#define relay_UPDATE_TYPE_DIRECT 0

#define relay_UPDATE_TYPE_ROUTE 1

#define relay_UPDATE_TYPE_CONTINUE 2

#define relay_SLICE_SECONDS 10.0

#define relay_CLIENT_ROUTE_TIMEOUT 20.0

#define relay_ROUTE_REQUEST_TIMEOUT 10.0

#define relay_ROUTE_REQUEST_SEND_TIME 0.25

#define relay_CONTINUE_REQUEST_TIMEOUT 10.0

#define relay_CONTINUE_REQUEST_SEND_TIME 0.25

#define relay_FLAGS_BAD_ROUTE_TOKEN (1 << 0)

#define relay_FLAGS_NO_ROUTE_TO_CONTINUE (1 << 1)

#define relay_FLAGS_PREVIOUS_UPDATE_STILL_PENDING (1 << 2)

#define relay_FLAGS_BAD_CONTINUE_TOKEN (1 << 3)

#define relay_FLAGS_ROUTE_EXPIRED (1 << 4)

#define relay_FLAGS_ROUTE_REQUEST_TIMED_OUT (1 << 5)

#define relay_FLAGS_CONTINUE_REQUEST_TIMED_OUT (1 << 6)

#define relay_FLAGS_ROUTE_TIMED_OUT (1 << 7)

#define relay_PACKET_TYPE_ROUTE_REQUEST 1

#define relay_PACKET_TYPE_ROUTE_RESPONSE 2

#define relay_PACKET_TYPE_CLIENT_TO_SERVER 3

#define relay_PACKET_TYPE_SERVER_TO_CLIENT 4

#define relay_PACKET_TYPE_SESSION_PING 5

#define relay_PACKET_TYPE_SESSION_PONG 6

#define relay_PACKET_TYPE_CONTINUE_REQUEST 7

#define relay_PACKET_TYPE_CONTINUE_RESPONSE 8

#define relay_PACKET_TYPE_CLIENT_PING 9

#define relay_PACKET_TYPE_CLIENT_PONG 10

#define relay_PACKET_TYPE_RELAY_PING 11

#define relay_PACKET_TYPE_RELAY_PONG 12

#define relay_PACKET_TYPE_SERVER_PING 13

#define relay_PACKET_TYPE_SERVER_PONG 14

#define relay_RELAY_PING_TOKEN_BYTES 32

#define relay_RELAY_PING_KEY_BYTES 32

/**
 * XChaCha20-Poly1305 nonce size in bytes (matches relay-xdp-common XCHACHA20POLY1305_NONCE_SIZE).
 */
#define relay_XCHACHA_NONCE_BYTES 24

/**
 * XChaCha20-Poly1305 key size in bytes (matches relay-xdp-common CHACHA20POLY1305_KEY_SIZE).
 */
#define relay_XCHACHA_KEY_BYTES 32

/**
 * Poly1305 authentication tag appended to ciphertext.
 */
#define relay_XCHACHA_TAG_BYTES 16

/**
 * SHA-256 output size.
 */
#define relay_SHA256_BYTES 32

#define relay_ROUTE_TOKEN_BYTES 71

#define relay_CONTINUE_TOKEN_BYTES 17

#define relay_ROUTE_RESPONSE_BYTES (relay_PACKET_BODY_OFFSET + relay_HEADER_BYTES)

#define relay_SESSION_PING_BYTES ((relay_PACKET_BODY_OFFSET + relay_HEADER_BYTES) + 8)

#define relay_SESSION_PONG_BYTES ((relay_PACKET_BODY_OFFSET + relay_HEADER_BYTES) + 8)

#define relay_CONTINUE_RESPONSE_BYTES (relay_PACKET_BODY_OFFSET + relay_HEADER_BYTES)

#define relay_CLIENT_PING_BYTES ((((relay_PACKET_BODY_OFFSET + 8) + 8) + 8) + relay_RELAY_PING_TOKEN_BYTES)

#define relay_CLIENT_PONG_BYTES ((relay_PACKET_BODY_OFFSET + 8) + 8)

#define relay_RELAY_PING_BYTES ((((relay_PACKET_BODY_OFFSET + 8) + 8) + 1) + relay_RELAY_PING_TOKEN_BYTES)

#define relay_RELAY_PONG_BYTES (relay_PACKET_BODY_OFFSET + 8)

#define relay_SERVER_PING_BYTES (((relay_PACKET_BODY_OFFSET + 8) + 8) + relay_RELAY_PING_TOKEN_BYTES)

#define relay_SERVER_PONG_BYTES (relay_PACKET_BODY_OFFSET + 8)

#define relay_CLIENT_STATE_CLOSED 0

#define relay_CLIENT_STATE_OPEN 1

#define relay_CLIENT_STATE_ERROR -1

#define relay_SERVER_STATE_CLOSED 0

#define relay_SERVER_STATE_OPEN 1

#endif  /* RELAY_GENERATED_H */
