/* relay-sdk - Auto-generated by cbindgen. DO NOT EDIT. */

#ifndef RELAY_GENERATED_H
#define RELAY_GENERATED_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define relay_REPLAY_PROTECTION_BUFFER_SIZE 1024

#define relay_PING_HISTORY_ENTRY_COUNT 1024

#define relay_PING_SAFETY 1.0

#define relay_BANDWIDTH_LIMITER_INTERVAL 1.0

#define relay_PACKET_LOSS_TRACKER_HISTORY 1024

#define relay_PACKET_LOSS_TRACKER_SAFETY 30

#define relay_ADDRESS_NONE 0

#define relay_ADDRESS_IPV4 1

#define relay_ADDRESS_IPV6 2

#define relay_ADDRESS_BYTES_IPV4 6

#define relay_ADDRESS_BYTES 19

#define relay_IPV4_HEADER_BYTES 20

#define relay_UDP_HEADER_BYTES 8

/**
 * Relay packet header (sequence + session_id + session_version + SHA-256 prefix).
 */
#define relay_HEADER_BYTES 25

/**
 * Maximum packet buffer size.
 */
#define relay_MAX_PACKET_BYTES 1384

/**
 * Maximum relay payload (MTU).
 */
#define relay_MTU 1200

/**
 * Byte offset of packet body (after type + pittle + chonkle = 18 bytes).
 */
#define relay_PACKET_BODY_OFFSET 18

#define relay_SESSION_PRIVATE_KEY_BYTES 32

#define relay_ENCRYPTED_ROUTE_TOKEN_BYTES 111

#define relay_ENCRYPTED_CONTINUE_TOKEN_BYTES 57

#define relay_MAX_TOKENS 7

#define relay_UPDATE_TYPE_DIRECT 0

#define relay_UPDATE_TYPE_ROUTE 1

#define relay_UPDATE_TYPE_CONTINUE 2

#define relay_SLICE_SECONDS 10.0

#define relay_CLIENT_ROUTE_TIMEOUT 20.0

#define relay_ROUTE_REQUEST_TIMEOUT 10.0

#define relay_ROUTE_REQUEST_SEND_TIME 0.25

#define relay_CONTINUE_REQUEST_TIMEOUT 10.0

#define relay_CONTINUE_REQUEST_SEND_TIME 0.25

#define relay_FLAGS_BAD_ROUTE_TOKEN (1 << 0)

#define relay_FLAGS_NO_ROUTE_TO_CONTINUE (1 << 1)

#define relay_FLAGS_PREVIOUS_UPDATE_STILL_PENDING (1 << 2)

#define relay_FLAGS_BAD_CONTINUE_TOKEN (1 << 3)

#define relay_FLAGS_ROUTE_EXPIRED (1 << 4)

#define relay_FLAGS_ROUTE_REQUEST_TIMED_OUT (1 << 5)

#define relay_FLAGS_CONTINUE_REQUEST_TIMED_OUT (1 << 6)

#define relay_FLAGS_ROUTE_TIMED_OUT (1 << 7)

#define relay_PACKET_TYPE_ROUTE_REQUEST 1

#define relay_PACKET_TYPE_ROUTE_RESPONSE 2

#define relay_PACKET_TYPE_CLIENT_TO_SERVER 3

#define relay_PACKET_TYPE_SERVER_TO_CLIENT 4

#define relay_PACKET_TYPE_SESSION_PING 5

#define relay_PACKET_TYPE_SESSION_PONG 6

#define relay_PACKET_TYPE_CONTINUE_REQUEST 7

#define relay_PACKET_TYPE_CONTINUE_RESPONSE 8

#define relay_PACKET_TYPE_CLIENT_PING 9

#define relay_PACKET_TYPE_CLIENT_PONG 10

#define relay_PACKET_TYPE_RELAY_PING 11

#define relay_PACKET_TYPE_RELAY_PONG 12

#define relay_PACKET_TYPE_SERVER_PING 13

#define relay_PACKET_TYPE_SERVER_PONG 14

#define relay_RELAY_PING_TOKEN_BYTES 32

#define relay_RELAY_PING_KEY_BYTES 32

#define relay_CLIENT_STATE_CLOSED 0

#define relay_CLIENT_STATE_OPEN 1

#define relay_CLIENT_STATE_ERROR -1

/**
 * XChaCha20-Poly1305 nonce size in bytes (matches relay-xdp-common XCHACHA20POLY1305_NONCE_SIZE).
 */
#define relay_XCHACHA_NONCE_BYTES 24

/**
 * XChaCha20-Poly1305 key size in bytes (matches relay-xdp-common CHACHA20POLY1305_KEY_SIZE).
 */
#define relay_XCHACHA_KEY_BYTES 32

/**
 * Poly1305 authentication tag appended to ciphertext.
 */
#define relay_XCHACHA_TAG_BYTES 16

/**
 * SHA-256 output size.
 */
#define relay_SHA256_BYTES 32

#define relay_ROUTE_RESPONSE_BYTES (relay_PACKET_BODY_OFFSET + relay_HEADER_BYTES)

#define relay_SESSION_PING_BYTES ((relay_PACKET_BODY_OFFSET + relay_HEADER_BYTES) + 8)

#define relay_SESSION_PONG_BYTES ((relay_PACKET_BODY_OFFSET + relay_HEADER_BYTES) + 8)

#define relay_CONTINUE_RESPONSE_BYTES (relay_PACKET_BODY_OFFSET + relay_HEADER_BYTES)

#define relay_CLIENT_PING_BYTES ((((relay_PACKET_BODY_OFFSET + 8) + 8) + 8) + relay_RELAY_PING_TOKEN_BYTES)

#define relay_CLIENT_PONG_BYTES ((relay_PACKET_BODY_OFFSET + 8) + 8)

#define relay_RELAY_PING_BYTES ((((relay_PACKET_BODY_OFFSET + 8) + 8) + 1) + relay_RELAY_PING_TOKEN_BYTES)

#define relay_RELAY_PONG_BYTES (relay_PACKET_BODY_OFFSET + 8)

#define relay_SERVER_PING_BYTES (((relay_PACKET_BODY_OFFSET + 8) + 8) + relay_RELAY_PING_TOKEN_BYTES)

#define relay_SERVER_PONG_BYTES (relay_PACKET_BODY_OFFSET + 8)

#define relay_SERVER_STATE_CLOSED 0

#define relay_SERVER_STATE_OPEN 1

#define relay_ROUTE_TOKEN_BYTES 71

#define relay_CONTINUE_TOKEN_BYTES 17

/**
 * Opaque handle for a relay game-client session.
 * Created by `relay_client_create`, destroyed by `relay_client_destroy`.
 */
typedef struct relay_RelayClient relay_RelayClient;

/**
 * Opaque handle for a relay game-server session.
 * Created by `relay_server_create`, destroyed by `relay_server_destroy`.
 */
typedef struct relay_RelayServer relay_RelayServer;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new relay client.
 * Returns null on failure (invalid bind_address string).
 * The returned pointer must be freed with `relay_client_destroy`.
 */
struct relay_RelayClient *relay_client_create(const char *bind_address);

/**
 * Destroy a relay client previously created with `relay_client_create`.
 * Passing null is a no-op.
 */
void relay_client_destroy(struct relay_RelayClient *handle);

/**
 * Open a relay session to server at `server_address` (e.g. "1.2.3.4:7777").
 * `client_secret_key` must point to exactly SESSION_PRIVATE_KEY_BYTES (32) bytes.
 * No-op if handle is null or server_address is invalid.
 */
void relay_client_open_session(struct relay_RelayClient *handle,
                               const char *server_address,
                               const uint8_t *client_secret_key);

/**
 * Close the current relay session.
 * No-op if handle is null.
 */
void relay_client_close_session(struct relay_RelayClient *handle);

/**
 * Queue a game payload for sending via relay (or direct if no route).
 * `data` must point to `bytes` bytes. No-op if handle is null.
 */
void relay_client_send_packet(struct relay_RelayClient *handle, const uint8_t *data, int bytes);

/**
 * Pop the next received game payload into `out` (caller-provided buffer of `max_bytes`).
 * Returns the number of bytes written, or 0 if no packet is available.
 * No-op and returns 0 if handle is null.
 */
int relay_client_recv_packet(struct relay_RelayClient *handle, uint8_t *out, int max_bytes);

/**
 * Return the current route flags bitmask for this client.
 * Flags encode token validation errors and route state.
 * See FLAGS_BAD_ROUTE_TOKEN, FLAGS_BAD_CONTINUE_TOKEN, etc. in relay_generated.h.
 * Returns 0 if handle is null.
 */
uint32_t relay_client_flags(struct relay_RelayClient *handle);

/**
 * Create a new relay server.
 * Returns null on failure (invalid bind_address string).
 * The returned pointer must be freed with `relay_server_destroy`.
 */
struct relay_RelayServer *relay_server_create(const char *bind_address);

/**
 * Destroy a relay server previously created with `relay_server_create`.
 * Passing null is a no-op.
 */
void relay_server_destroy(struct relay_RelayServer *handle);

/**
 * Register a session (called when relay-backend pushes session keys via HTTP).
 * `session_private_key` must point to exactly SESSION_PRIVATE_KEY_BYTES (32) bytes.
 * `relay_address` is the last relay hop address string (e.g. "10.0.0.1:4000").
 * No-op if handle is null.
 */
void relay_server_register_session(struct relay_RelayServer *handle,
                                   uint64_t session_id,
                                   uint8_t session_version,
                                   const uint8_t *session_private_key,
                                   const char *relay_address);

/**
 * Expire (remove) a session.
 * No-op if handle is null or session not found.
 */
void relay_server_expire_session(struct relay_RelayServer *handle, uint64_t session_id);

/**
 * Send a game payload to `session_id` via the last relay hop.
 * `data` must point to `bytes` bytes.
 * `magic` must point to 8 bytes.
 * `from_address` is the server's own address string (e.g. "10.0.0.2:9000").
 * Returns 0 on success, -1 if handle is null or payload is too large.
 */
int relay_server_send_packet(struct relay_RelayServer *handle,
                             uint64_t session_id,
                             const uint8_t *data,
                             int bytes,
                             const uint8_t *magic,
                             const char *from_address);

/**
 * Return the session_id from the last failed send, or 0 if no error is pending.
 * Also drains any pending notifications to refresh the error state.
 * Call `relay_server_clear_last_send_error` after handling the error.
 */
uint64_t relay_server_last_send_error(struct relay_RelayServer *handle);

/**
 * Clear the last send error recorded on the server handle.
 */
void relay_server_clear_last_send_error(struct relay_RelayServer *handle);

/**
 * Pop the next received game payload into `out` (caller-provided buffer of `max_bytes`).
 * On success, writes the originating session_id into `*out_session_id`.
 * Returns the number of bytes written, or 0 if no packet is available.
 * No-op and returns 0 if handle is null.
 */
int relay_server_recv_packet(struct relay_RelayServer *handle,
                             uint64_t *out_session_id,
                             uint8_t *out,
                             int max_bytes);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RELAY_GENERATED_H */
